# Multiple Linear Regression

In [1]:
# Import packages and classes
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
%matplotlib inline

In [3]:
# Read the cars.csv file
url="https://raw.githubusercontent.com/ShilpaSayuraML/data-science-mastsr/master/data/cars.csv"
data = pd.read_csv(url)
data.head()

          Car       Model  Volume  Weight  CO2
0      Toyoty        Aygo    1000     790   99
1  Mitsubishi  Space Star    1200    1160   95
2       Skoda      Citigo    1000     929   95
3        Fiat         500     900     865   90
4        Mini      Cooper    1500    1140  105

In [5]:
# Print first 5 data
data.describe()

            Volume       Weight         CO2
count    36.000000    36.000000   36.000000
mean   1611.111111  1292.277778  102.027778
std     388.975047   242.123889    7.454571
min     900.000000   790.000000   90.000000
25%    1475.000000  1117.250000   97.750000
50%    1600.000000  1329.000000   99.000000
75%    2000.000000  1418.250000  105.000000
max    2500.000000  1746.000000  120.000000

In [8]:
# Print information of Dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Car     36 non-null     object
 1   Model   36 non-null     object
 2   Volume  36 non-null     int64
 3   Weight  36 non-null     int64
 4   CO2     36 non-null     int64
dtypes: int64(3), object(2)
memory usage: 1.5+ KB

In [10]:
# Divide the data into “Attributes” and “labels”
X = data[['Weight', 'Volume']]
y = data['CO2']

In [11]:
# Split 80% of the data to the training set while 20% of the data to test set

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [12]:
# Create a Linear Regression model and fit it
regressor =LinearRegression(fit_intercept=True)
regressor.fit(X_train,y_train)

LinearRegression()

In [13]:
# Getting Results
print('Linear Model Coeff (m) =' , regressor.coef_)
print('Linear Model Coeff (b) =' , regressor.intercept_)

Linear Model Coeff (m) = [0.00728963 0.0076251 ]
Linear Model Coeff (b) = 80.57109791690918

In [14]:
# Predicting the data
y_predict=regressor.predict(X_test)
print(y_predict)

[108.54900223 104.31804036 102.72161109 108.2836746  106.53416307
 102.46647399  96.10255102  94.96826943]

In [16]:
# Prediction the CO2 emission of car using Weight and Volume Value of the car directly
print('---------[700,900]---------')
wg = 700
vol = 900
co2 = regressor.predict([[wg,vol]])
print(co2)
print('--------[1100,1500]----------')
wg = 1100
vol = 1500
co2 = regressor.predict([[wg,vol]])
print(co2)
print('--------[1500,2500]----------')
wg = 1500
vol = 2500
co2 = regressor.predict([[wg,vol]])
print(co2)

---------[700,900]---------
[92.53643345]
--------[1100,1500]----------
[100.02734838]
--------[1500,2500]----------
[110.56830489]

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(